# Generated by Django 5.0.6 on 2024-08-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="memory",
            field=models.TextField(default=""),
        ),
    ]
