# Generated by Django 5.0.6 on 2024-06-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='uer',
            new_name='user',
        ),
    ]
